---
# the configuration file of cmdx - task runner
# https://github.com/suzuki-shunsuke/cmdx
tasks:
- name: test
  short: t
  description: test
  usage: test
  script: go test ./... -race -covermode=atomic
- name: vet
  short: v
  description: go vet
  usage: go vet
  script: go vet ./...
- name: lint
  short: l
  description: lint the go code
  usage: lint the go code
  script: golangci-lint run
- name: release
  short: r
  description: release the new version
  usage: release the new version
  script: |
    git tag "{{.version}}"
    git push origin "{{.version}}"
  args:
  - name: version
    required: true
    validate:
    - regexp: "^v\\d+\\.\\d+.\\d+(-\\d+)?$"
- name: build
  description: go build
  usage: go build
  script: go build -o dist/clivm ./cmd/clivm
- name: coverage
  short: c
  description: coverage test
  usage: coverage test
  script: "bash scripts/coverage.sh {{.target}}"
  args:
  - name: target
- name: wire
  short: w
  description: google/wire
  usage: google/wire
  script: "wire ./..."
- name: js
  description: Generate JSON Schema
  usage: Generate JSON Schema
  script: "go run ./cmd/gen-jsonschema"
- name: validate-js
  description: Validate clivm.yaml and registry.yaml with JSON Schema
  usage: Validate clivm.yaml and registry.yaml with JSON Schema
  # https://ajv.js.org/packages/ajv-cli.html
  script: |
    ajv --spec=draft2020 -s json-schema/clivm-yaml.json -d clivm.yaml
    ajv --spec=draft2020 -s json-schema/registry.json -d tests/registry.yaml
