---
name: actionlint
on:
  push:
    branches: [dummy] # TODO enable
    paths:
    - .github/**
  pull_request:
    branches: [dummy] # TODO enable
    paths:
    - .github/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: clivm/clivm-installer@v1.0.0
      with:
        clivm_version: v1.14.0
    - run: actionlint
