---
name: integration-test
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CLIVM_LOG_LEVEL: debug
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3.2.0
      with:
        go-version: '1.18.3'
        cache: true

    - run: go install ./cmd/aqua
    - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/clivm/bin" >> "$GITHUB_PATH"
    - run: echo "CLIVM_GLOBAL_CONFIG=$PWD/tests/clivm-global.yaml:$PWD/tests/clivm-global-2.yaml" >> "$GITHUB_ENV"
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "x-motemen/ghq" | aqua g -f -
    - run: echo "local,clivm/clivm-installer" | aqua -c tests/clivm-global.yaml g -f -
    - run: aqua g x-motemen/ghq clivm/clivm-installer
    - run: echo cli/cli | aqua g -f - x-motemen/ghq clivm/clivm-installer

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: tfenv --version
    - run: aqua -c tests/clivm-global.yaml g local,kubernetes-sigs/kustomize
    - run: btop -v
    - run: btop -v
      env:
        CLIVM_EXPERIMENTAL_X_SYS_EXEC: "true"
    - run: wire --help
    - run: gox --help
    - run: bats -v
    - run: github-compare -v
    - run: terrafmt version

    - name: output bash completion
      run: aqua completion bash
    - name: output zsh completion
      run: aqua completion zsh

    - run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - run: git diff aqua.yaml
      working-directory: tests

    - name: "Test generate-registry"
      run: aqua gr cli/cli
    - name: "Test generate-registry (rust)"
      run: aqua gr XAMPPRocky/tokei

    - name: "test version_source: github_tag"
      run: aqua -c clivm-global.yaml g local,mitchellh/gox
      working-directory: tests

    # Test if global configuration files are read in `aqua list` and `aqua g`
    - run: aqua g suzuki-shunsuke/cmdx
      working-directory: /tmp
    - run: aqua list
      working-directory: /tmp

    - run: clivm-installer -v v0.8.1 -i /tmp/aqua

  build-windows:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CLIVM_LOG_LEVEL: debug
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3.2.0
      with:
        go-version: '1.18.3'
        cache: true

    - run: go install ./cmd/aqua
    - run: echo "$HOME/AppData/Local/clivm/bin" >> "$GITHUB_PATH"
    - run: echo "CLIVM_GLOBAL_CONFIG=$PWD/tests/clivm-global.yaml:$PWD/tests/clivm-global-2.yaml" >> "$GITHUB_ENV"
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "x-motemen/ghq" | aqua g -f -
    - run: aqua g x-motemen/ghq clivm/clivm-installer
    - run: echo cli/cli | aqua g -f - x-motemen/ghq clivm/clivm-installer

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: aqua -c tests/clivm-global.yaml g local,kubernetes-sigs/kustomize
    - run: wire --help
    - run: gox --help
    - run: github-compare -v
    - run: terrafmt version

    - run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - run: git diff aqua.yaml
      working-directory: tests

    - name: "Test generate-registry"
      run: aqua gr cli/cli
    - name: "Test generate-registry (rust)"
      run: aqua gr XAMPPRocky/tokei

    - name: "test version_source: github_tag"
      run: aqua -c clivm-global.yaml g local,mitchellh/gox
      working-directory: tests

    # Test if global configuration files are read in `aqua list` and `aqua g`
    - run: aqua g suzuki-shunsuke/cmdx
      working-directory: ${{ env.HOME }}
    - run: aqua list
      working-directory: ${{ env.HOME }}

  build-windows-pwsh:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CLIVM_LOG_LEVEL: debug
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3.2.0
      with:
        go-version: '1.18.3'
        cache: true

    - run: go install ./cmd/aqua
    - run: echo "$HOME\AppData\Local\clivm\bat" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - run: echo "CLIVM_GLOBAL_CONFIG=$PWD\tests\clivm-global.yaml;$PWD\tests\clivm-global-2.yaml" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "x-motemen/ghq" | aqua g -f -
    - run: aqua g x-motemen/ghq clivm/clivm-installer
    - run: echo cli/cli | aqua g -f - x-motemen/ghq clivm/clivm-installer

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: aqua -c tests/clivm-global.yaml g local,kubernetes-sigs/kustomize
    - run: wire --help
    - run: gox --help
    - run: github-compare -v
    - run: terrafmt version

    - run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - run: git diff aqua.yaml
      working-directory: tests

    - name: "Test generate-registry"
      run: aqua gr cli/cli
    - name: "Test generate-registry (rust)"
      run: aqua gr XAMPPRocky/tokei

    - name: "test version_source: github_tag"
      run: aqua -c clivm-global.yaml g local,mitchellh/gox
      working-directory: tests

    # Test if global configuration files are read in `aqua list` and `aqua g`
    - run: aqua g suzuki-shunsuke/cmdx
      working-directory: ${{ env.HOME }}
    - run: aqua list
      working-directory: ${{ env.HOME }}
