---
name: test-docker-prebuilt
on: workflow_call
jobs:
  test-docker:
    # Test Dockerfile
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - run: docker build -t aquaproj-aqua-dev -f Dockerfile-prebuilt .
